### ISSUE TITLE
Remove upper bound on python_requires

### ISSUE THREAD

**Issue by matthewfeickert** [saforem2/l2hmc-qcd#59]
(I'm moving between meetings so can iterate on this more later, so excuse the very brief Issue for now).

At the moment the project has an upper bound on `python_requires`

https://github.com/saforem2/l2hmc-qcd/blob/2eb6ee63cc0c53b187e6d716f4c12f418c8b8515/setup.py#L165

Assuming that you're intending `l2hmc` to [be a library and not an application](https://iscinumpy.dev/post/app-vs-library/), then I would highly recommend removing this for the reasons summarized in Henry's [detailed blog post on the subject](https://iscinumpy.dev/post/bound-version-constraints/).

Congrats on getting [`l2hmc` up on PyPI](https://pypi.org/project/l2hmc/) though! :snake: :rocket:

**Comment by saforem2** [comment]
from Henry's [detailed blog post on the subject](https://iscinumpy.dev/post/bound-version-constraints/):

> Also be warned, I pick on [Poetry](https://python-poetry.org/) quite a bit. The rising popularity of [Poetry](https://python-poetry.org/) is likely due to the simplicity of having one tool vs. many for packaging, but it happens to also have a special dependency solver, a new upper bound syntax, and a strong recommendation to always limit upper versions - in direct opposition to members of the Python core developer team and PyPA developers.

LOL, another reason I didn't want to close the other issue is because I'm currently using poetry to build and publish even though I knew it wasn't really a _best practice_, and have been meaning to ditch it but just hadn't gotten around to it

> Assuming that you're intending l2hmc to [be a library and not an application](https://iscinumpy.dev/post/app-vs-library/)

It's interesting. To be honest I'm not really sure what my ultimate goal is for this repo / project. It started (and still mostly is) really just for exploring new sampling techniques for (a pretty niche) scientific application, but as I've thought more about it I think there are probably certain parts that might be of interest / use to a larger community 🤷🏻‍♂️

**Comment by saforem2** [comment]
Easy fix: ditch `setup.py` entirely and strictly use `pyproject.toml` instead

done ✅
